# 1. Identidade e Porta do Serviço
spring.application.name=ms-identity
server.port=8081

# 2. Conexão com o Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB_IDENTITY}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Monitoramento e Saúde (NFR-13)
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# 5. Configurações de Segurança (JWT) - Personalizadas
autobid.jwt.secret=${JWT_SECRET:secret-chave-padrao-muito-longa-e-segura-2026}
autobid.jwt.expiration=86400000

# 6. Mensageria e Cache (RabbitMQ e Redis)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBIT_USER}
spring.rabbitmq.password=${RABBIT_PASS}

spring.data.redis.host=localhost
spring.data.redis.port=${REDIS_PORT}
